# Practical - 1

1. Write a python program to create 3x3 matrix and perform matrix addition using numpy
2. Create a numpy array containing 10 random ints and find their mean and standard devition
3. Implement a function to calculate the dot product of two given array using numpy

In [1]:
import numpy as np

**1. Write a python program to create 3x3 matrix and perform matrix addition using numpy**


In [2]:
mat1 = np.reshape(np.arange(9), (3, 3))
mat2 = np.reshape(np.arange(9, 18), (3, 3))
mat1, mat2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]))

In [19]:
np.add(mat1, mat2)

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

 2. Create a numpy array containing 10 random ints and find their mean and standard devition 

In [27]:
arr = np.random.randint(0, 100, size=(10))
arr

array([51, 57,  0, 46, 50, 27, 71, 46, 64,  7], dtype=int32)

In [28]:
# Standard deviation:
np.std(arr)

np.float64(22.22813532440362)

In [29]:
# Mean:
np.mean(arr)

np.float64(41.9)

 3. Implement a function to calculate the dot product of two given array using numpy 

In [25]:
arr1 = np.reshape(np.arange(9), (3, 3))
arr2 = np.reshape(np.arange(9, 18), (3, 3))
arr1, arr2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]))

In [26]:
np.dot(arr1, arr2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

1. What is the purpose of NumPy Library in Python
2. How do you create a NumPy array
3. What are the advantages of using NumPy array over Python List 

Here are the answers to your questions about NumPy:

---

### **1. What is the purpose of NumPy Library in Python?**

The purpose of NumPy is to provide support for large, multi-dimensional arrays and matrices along with a collection of mathematical functions to operate on these arrays efficiently.


### **2. How do you create a NumPy array?**

```python
# Step-1: Import NumPy
import numpy as np

# Step-2: Creating array from list
arr1 = np.array([1, 2, 3, 4])

# Step-3: Print NumPy array
print(arr1)
```


### **3. What are the advantages of using NumPy array over Python List?**
Advantages of NumPy array over Python List:

* Much faster
* Uses less memory  
* Supports advanced math ops
* Built-in for matrices/tensors